name: Lecture7

on: push

jobs:
  sample-session:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: System info
        run: |
          erl -eval 'erlang:display({otp_release, erlang:system_info(otp_release)}), halt().' -noshell
      - name: Build
        run: rebar3 release
      - name: Test
        run: rebar3 ct -v
      - name: Run app
        run: _build/default/rel/cache/bin/cache daemon
      - name: Sample session
        run: ./demo.sh
